# Extensions Repository - use the following format
# ------------------------------------------------
# <extension name> = ["file.py", "author", "description"]
sample=["sample.py", "billyeatcookies", "Hello world, sample extension"]

typo=["typo.py", "Do typing tests inside biscuit!"]
monkey=["monkey.py", "ltaoist", "Support for Monkey projects"]
